[package]
name = "log-result-proc-macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
log = { version = "^0.4.17", features = ["std", "max_level_debug", "release_max_level_debug"] }
